apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: front-end
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 7b8f13c7-kr1-registry.container.nhncloud.com/nct-web/nct-web:15
        name: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-credential-front
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: front-end
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
