apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: front-end
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 7b8f13c7-kr1-registry.container.nhncloud.com/nct-web/nct-web:21
        name: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-credential-front
        resources:
          requests:
            memory: 100Mi
            cpu: 60m
          limits:
            memory: 100Mi
            cpu: 60m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: front-end
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: front-end
spec:
  maxReplicas: 15
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 30
