apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tomcat
  name: tomcat
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: keviness0720/test05-was:v1.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-svc
  namespace: back-end
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: tomcat
  type: ClusterIP
  clusterIP: 10.254.0.20
status:
  loadBalancer: {}
