name: Build and Push Docker Image to NHN Cloud NCR

on:
  push:
    branches:
      - was

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to NHN Cloud NCR
      run: |
        echo "${{ secrets.NHN_SECRET_ACCESS_KEY }}" | docker login 2ea45060-kr1-registry.container.nhncloud.com/nct-was \
          -u "${{ secrets.NHN_ACCESS_KEY_ID }}" \
          --password-stdin

    - name: Build Docker image
      run: docker build -t 2ea45060-kr1-registry.container.nhncloud.com/nct-was/nct-was:${{ github.run_number }} .

    - name: Push Docker image to NHN Cloud NCR
      run: docker push 2ea45060-kr1-registry.container.nhncloud.com/nct-was/nct-was:${{ github.run_number }}

    - name: Log out from NHN Cloud NCR
      run: docker logout 2ea45060-kr1-registry.container.nhncloud.com
